runtime: nodejs10

instance_class: F2

handlers:
  - url: /public/css
    static_dir: css

  - url: /public/js
    static_dir: js

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
